#pragma once

// Root CA for aldervon.com HTTPS APIs.
static const char aldervon_root_ca_pem[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDpzCCA02gAwIBAgIRANyDJuvROIaPDf1qluh1HHcwCgYIKoZIzj0EAwIwOzEL\n"
    "MAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczEMMAoG\n"
    "A1UEAxMDV0UxMB4XDTI2MDIxMzE2MTc1MFoXDTI2MDUxNDE3MTYwMlowFzEVMBMG\n"
    "A1UEAxMMYWxkZXJ2b24uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESBiy\n"
    "7FQPywc0TCpyesMpfg6BffqmAK40l4qGtzzuq1Mx6MZ+IeJNaVakzwn8dN4f4qKu\n"
    "/C9rUUAVipTKtx0f6qOCAlQwggJQMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAK\n"
    "BggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBS0w9lxE0fkMtMOLH1B\n"
    "PImnhoT47zAfBgNVHSMEGDAWgBSQd5I1Z8T/qMyp5nvZgHl7zJP5ODBeBggrBgEF\n"
    "BQcBAQRSMFAwJwYIKwYBBQUHMAGGG2h0dHA6Ly9vLnBraS5nb29nL3Mvd2UxLzNJ\n"
    "TTAlBggrBgEFBQcwAoYZaHR0cDovL2kucGtpLmdvb2cvd2UxLmNydDAnBgNVHREE\n"
    "IDAeggxhbGRlcnZvbi5jb22CDiouYWxkZXJ2b24uY29tMBMGA1UdIAQMMAowCAYG\n"
    "Z4EMAQIBMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jLnBraS5nb29nL3dlMS9r\n"
    "OUQwTGNRY0ZUby5jcmwwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQCWl2S/VViX\n"
    "rfdDh2g3CEJ36fA61fak8zZuRqQ/D8qpxgAAAZxYAkhtAAAEAwBGMEQCIBS/NDXu\n"
    "t1d3Tf2iSguMFPsxVQ1t2jkD+GFZxKU6ieB3AiBhhJtvB1PVpyU9dQwheoCjV+J5\n"
    "JKUxDSQPyFhnfJRvXgB2ANFuqaVoB35mNaA/N6XdvAOlPEESFNSIGPXpMbMjy5UE\n"
    "AAABnFgCSSAAAAQDAEcwRQIgIt7OuGNyd/N0yskaPzTRvJofaX6Bm1h3KG89tjaS\n"
    "X9sCIQDMeR36jgAUhESg4l86W0Or4SEHpqK6xRXtemV7GUbNFDAKBggq\n"
    "-----END CERTIFICATE-----\n";
