; PlatformIO – ESP32-C6 Mini with ESP-IDF
[platformio]
src_dir = main

[env:esp32-c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
extra_scripts = post:scripts/post_build_copy_www.py

monitor_speed = 115200
