; PlatformIO – ESP32-C6 Mini with ESP-IDF
[platformio]
src_dir = main

[env:esp32-c6]
platform = espressif32
board = AldervendAdapterBoard
framework = espidf
build_flags = !python build_flags.py
board_build.partitions = partitions.csv

monitor_speed = 115200
